import { RequiredInput } from "../interfaces/requireInput";

export const TASK_REQUIRED_INPUTS: RequiredInput[] = [
  {
    type: "text",
    name: "title",
    label: "label.taskTitle",
    required: true,
    className: "form-control",
    autoComplete: "off",
  },
  {
    type: "text",
    name: "description",
    label: "label.taskDescription",
    required: true,
    className: "form-control",
    autoComplete: "off",
  },
  {
    type: "text",
    name: "members",
    label: "label.projectMembers",
    required: true,
    className: "project-pop__input",
    autoComplete: "off",
  },
  {
    type: "text",
    name: "checkList",
    label: "label.checkList",
    required: true,
    className: "form-control",
    autoComplete: "off",
  },
  {
    type: "date",
    name: "deadLine",
    label: "label.deadline",
    required: true,
    className: "form-control",
    autoComplete: "off",
    min: "1900-01-01",
    max: "2100-01-01",
  },
  {
    type: "select",
    name: "taskDepartment",
    label: "label.taskDepartment",
    required: true,
    className: "form-control",
    options: [
      { value: "label.pmValue", name: "Project Manager" },
      { value: "label.devValue", name: "Developer" },
      { value: "label.testerValue", name: "Designer" },
      { value: "label.testerValue", name: "Tester" },
    ],
  },
  {
    type: "select",
    name: "taskStatus",
    label: "label.taskStatus",
    required: false,
    className: "form-control",
    options: [
      { name: "To Do", value: "label.toDo" },
      { name: "In Progress", value: "label.inProgress" },
      { name: "On review", value: "label.onReview" },
      { name: "On testing", value: "label.onTesting" },
      { name: "Done", value: "label.done" },
      { name: "Canceled", value: "label.canceled" },
    ],
  },
];
